DROP TABLE LOAN;
DROP TABLE MEMBER;
DROP TABLE BOOK;
DROP TABLE BACKUP_MEMBER;
DROP TABLE BACKUP_BOOK;
REM ********************************************************************
REM 수정사항
REM 23/04/15 DROP TABLE 순서 MEMBER, BOOK , LOAN -> LOAN, MEMBER, BOOK
REM 23/04/15 나이계산 BETWEEN SYSDATE에서 트리거로 변경
REM 23/04/16 삭제복구용 테이블 생성 
REM 23/04/18 LoanID sequence로 변경
REM 23/04/18 모든 테이블 ID SEQ적용 DEFAULT

REM ********************************************************************

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 99999999
  NOCYCLE;

CREATE TABLE MEMBER(
    ID          VARCHAR2(20)    DEFAULT LPAD(MEMBER_SEQ.NEXTVAL,3,'0') CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
    NAME        VARCHAR2(20)    NOT NULL,
    BIRTHDAY    DATE            NOT NULL,
    ADDRESS     VARCHAR2(50)    NOT NULL,
    PHONENUMBER VARCHAR2(15)    CONSTRAINT MEMBER_UK UNIQUE,
    STARTDATE   DATE            DEFAULT SYSDATE,
    AGE         NUMBER
);

--CREATE TABLE MEMBER(
--    ID          VARCHAR2(8)     DEFAULT LPAD(MEMBER_SEQ.NEXTVAL,3,'0'), CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
--    NAME        VARCHAR2(20)    NOT NULL,
--    BIRTHDAY    DATE            NOT NULL,
--    ADDRESS     VARCHAR2(50)    NOT NULL,
--    PHONENUMBER VARCHAR2(15)    CONSTRAINT MEMBER_UK UNIQUE,
--    STARTDATE   DATE            DEFAULT SYSDATE,
--    AGE         NUMBER
--    );

DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 99999999
  NOCYCLE;
    
CREATE TABLE BOOK(
    BOOKID       VARCHAR2(20)     DEFAULT LPAD(BOOK_SEQ.NEXTVAL,3,'0') CONSTRAINT BOOK_ID_PK PRIMARY KEY,
    BOOKNAME     VARCHAR2(50)     NOT NULL,
    PUBLISHDATE  DATE            NOT NULL,
    STATUS       CHAR(1)         NOT NULL,CONSTRAINT STATUS_CK CHECK (STATUS IN ('T','F'))
    );


DROP SEQUENCE LOAN_SEQ;
CREATE SEQUENCE LOAN_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 99999999
  NOCYCLE;

CREATE TABLE LOAN(
    LOANID                    VARCHAR2(20)     DEFAULT LPAD(LOAN_SEQ.NEXTVAL,3,'0') CONSTRAINT LOAN_ID_PK PRIMARY KEY,
    MEMBERID                  VARCHAR2(20)     NOT NULL, CONSTRAINT LOAN_MEMBER_FK FOREIGN KEY(MEMBERID) 
                                                REFERENCES MEMBER(ID),
    BOOKID                    VARCHAR2(20)     NOT NULL, CONSTRAINT LOAN_BOOK_FK FOREIGN KEY(BOOKID)
                                                REFERENCES BOOK(BOOKID),
    LOANDATE                  DATE            DEFAULT SYSDATE,
    RETURNDATE                DATE            DEFAULT SYSDATE + 14,
    EXTENSIONAVAILABLE        CHAR(1)         NOT NULL, CONSTRAINT EXTENSION_CK 
                                                        CHECK(EXTENSIONAVAILABLE IN ('T','F'))

    );     
    
    


-- 생일을 기반으로 나이를 계산
CREATE OR REPLACE TRIGGER CALC_AGE
BEFORE INSERT OR UPDATE ON MEMBER
FOR EACH ROW
BEGIN
    :NEW.AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.BIRTHDAY) / 12);
END;
--UPDATE MEMBER SET AGE=TRUNC(MONTHS_BETWEEN(SYSDATE,BIRTHDAY)/12);
/

CREATE TABLE BACKUP_MEMBER(
    ID          VARCHAR2(8)     CONSTRAINT BACKUP_MEMBER_ID_PK PRIMARY KEY,
    NAME        VARCHAR2(20)    NOT NULL,
    BIRTHDAY    DATE            NOT NULL,
    ADDRESS     VARCHAR2(50)    NOT NULL,
    PHONENUMBER VARCHAR2(15)    CONSTRAINT BACKUP_MEMBER_UK UNIQUE,
    STARTDATE   DATE            DEFAULT SYSDATE,
    AGE         NUMBER
    );
    
CREATE TABLE BACKUP_BOOK(
    BOOKID       VARCHAR2(8)      CONSTRAINT BACKUP_BOOK_ID_PK PRIMARY KEY,
    BOOKNAME     VARCHAR2(20)     NOT NULL,
    PUBLISHDATE  DATE            NOT NULL,
    STATUS       CHAR(1)         NOT NULL,CONSTRAINT BACUP_STATUS_CK CHECK (STATUS IN ('T','F'))
    );

--유저정보삽입    
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'심민정','경기도 광명시','01050437629',TO_DATE('19981223','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'최경민','충청북도 청주시','01096647107',TO_DATE('19990123','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'최유림','경기도 광명시','01020271810',TO_DATE('19981223','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'홍길동','서울특별시 강남구','01012345678',TO_DATE('19900101','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'김철수','경기도 수원시','01055556666',TO_DATE('19951231','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'이영희','인천광역시 부평구','01077778888',TO_DATE('19891203','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'박민수','대구광역시 동구','01022223333',TO_DATE('19980214','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'임지우','부산광역시 동래구','01033334444',TO_DATE('20000902','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'최수진','전라남도 여수시','01099991111',TO_DATE('19871015','RRRR/MM/DD'));
INSERT INTO MEMBER(ID,NAME,ADDRESS,PHONENUMBER,BIRTHDAY)
            VALUES(LPAD(MEMBER_SEQ.NEXTVAL,3,'0'),'한지영','충청남도 천안시','01088889999',TO_DATE('19931111','RRRR/MM/DD'));

--책정보추가

INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES(LPAD(BOOK_SEQ.NEXTVAL,3,'0'),'파이썬',TO_DATE('20121115','RRRR/MM/DD'),'T');
INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES(LPAD(BOOK_SEQ.NEXTVAL,3,'0'),'자바',TO_DATE('20100625','RRRR/MM/DD'),'T');
INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES(LPAD(BOOK_SEQ.NEXTVAL,3,'0'),'데이터베이스',TO_DATE('20090714','RRRR/MM/DD'),'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), '자바의 정석', TO_DATE('20150101','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), 'C언어 입문', TO_DATE('20081020','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), '스위프트 프로그래밍', TO_DATE('20170110','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), '루비 기초', TO_DATE('20091205','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), '자바스크립트의 이해', TO_DATE('20130830','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), '파이썬 프로그래밍', TO_DATE('20181023','RRRR/MM/DD'), 'T');
INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHDATE, STATUS) VALUES (LPAD(BOOK_SEQ.NEXTVAL,3,'0'), 'HTML5 기초', TO_DATE('20101218','RRRR/MM/DD'), 'T');
COMMIT; 