--유저정보삽입    
INSERT INTO MEMBER(NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES('심민정','경기도 광명시','01050437629',TO_DATE('19981223','RRRR/MM/DD'));
INSERT INTO MEMBER(NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES('최경민','충청북도 청주시','01096647107',TO_DATE('19990123','RRRR/MM/DD'));
INSERT INTO MEMBER(NAME,ADDRESS,PHONENUMBER,BIRTHDAY) 
            VALUES('최유림','경기도 광명시','01020271810',TO_DATE('19981223','RRRR/MM/DD'));
COMMIT;

--ID + 1 통해 ID 삽입
SELECT TO_CHAR(MAX(ID)+1,'000') FROM MEMBER;

SELECT * FROM MEMBER;
commit;
--유저정보수정 (ID를 통해)
--이름 수정
UPDATE MEMBER SET NAME = '민정' WHERE ID = '001';
--주소 수정
UPDATE MEMBER SET ADDRESS = '경기도 수원시' WHERE ID = '001';
--전화번호 수정
UPDATE MEMBER SET PHONENUMBER = '01011111111' WHERE ID = '001';
--생일 수정
UPDATE MEMBER SET BIRTHDAY = TO_DATE('19991223','RRRR/MM/DD') WHERE ID = '001'; 
                    
ROLLBACK;
--유저정보삭제
delete from member where id>5;



--책정보추가
INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES('001','파이썬',TO_DATE('20121115','RRRR/MM/DD'),'T');
INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES('002','자바',TO_DATE('20100625','RRRR/MM/DD'),'T');
INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHDATE,STATUS) VALUES('003','데이터베이스',TO_DATE('20090714','RRRR/MM/DD'),'T');
COMMIT; 

--책 조회
SELECT * FROM BOOK;

--대출가능한 책 조회
SELECT * FROM SCOTT.BOOK WHERE STATUS = 'T';


--대출 상태 변경
UPDATE BOOK SET STATUS = 'F' WHERE BOOKNAME = '파이썬';

--책정보 수정
--책이름 수정
UPDATE SCOTT.BOOK SET BOOKNAME = '한국사' WHERE BOOKID = '001'; 

--출판일 수정
UPDATE SCOTT.BOOK SET PUBLISHDATE = TO_DATE('19991023','RRRR/MM/DD') WHERE ID = '001';
SELECT * FROM BOOK;
ROLLBACK;

SELECT * FROM BACKUP_BOOK;


--대출AON;
INSERT INTO LOAN(LOANID,MEMBERID,BOOKID,EXTENSIONAVAILABLE) VALUES('001','002','001','T');
UPDATE BOOK SET STATUS='F' WHERE BOOKID='001';
INSERT INTO LOAN(LOANID,MEMBERID,BOOKID,EXTENSIONAVAILABLE) VALUES('002','001','002','T');
UPDATE BOOK SET STATUS='F' WHERE BOOKID='002';
SELECT * FROM LOAN;
SELECT * FROM BOOK;

--대출 연장
UPDATE LOAN SET RETURNDATE=RETURNDATE+7
WHERE MEMBERID='001' AND BOOKID='002' AND EXTENSIONAVAILABLE='T';
--연장은 한번만 가능
UPDATE LOAN SET EXTENSIONAVAILABLE = 'F' WHERE MEMBERID='001' AND BOOKID='002';
SELECT * FROM LOAN WHERE EXTENSIONAVAILABLE = 'T';
--대출목록
SELECT LOAN.LOANID,LOAN.MEMBERID,LOAN.BOOKID,MEMBER.NAME ,BOOK.BOOKNAME, LOAN.LOANDATE,LOAN.RETURNDATE,
LOAN.EXTENSIONAVAILABLE FROM MEMBER,BOOK,LOAN
WHERE LOAN.MEMBERID=MEMBER.ID AND LOAN.BOOKID=BOOK.BOOKID;
COMMIT;

--번호에 따른 대출내역 확인
SELECT * FROM (SELECT LOAN.LOANID,LOAN.MEMBERID,LOAN.BOOKID,MEMBER.NAME ,BOOK.BOOKNAME, LOAN.LOANDATE,LOAN.RETURNDATE,
                        LOAN.EXTENSIONAVAILABLE FROM MEMBER,BOOK,LOAN
                        WHERE LOAN.MEMBERID=MEMBER.ID AND LOAN.BOOKID=BOOK.BOOKID) WHERE MEMBERID = '003';
--대여가능한 책 목록
SELECT * FROM BOOK WHERE STATUS='T';



--기타 등등
select * from member;
select to_char(max(id)+1,'000') from member;
delete from member where id>5;
commit;
SELECT * FROM MEMBER;

SELECT * FROM SCOTT.MEMBER WHERE ID = '001';

select * from backup_member;

DELETE FROM BACKUP_MEMBER;
ROLLBACK;

select * from book;
SELECT * FROM SCOTT.BOOK WHERE STATUS = 'T';
select * from loan;
delete from loan where loanid = '002';
commit;

SELECT * FROM (SELECT LOAN.LOANID,LOAN.MEMBERID,LOAN.BOOKID,MEMBER.NAME ,BOOK.BOOKNAME, LOAN.LOANDATE,LOAN.RETURNDATE,
                        LOAN.EXTENSIONAVAILABLE FROM MEMBER,BOOK,LOAN
                        WHERE LOAN.MEMBERID=MEMBER.ID AND LOAN.BOOKID=BOOK.BOOKID) WHERE MEMBERID = '003';
SELECT LOAN.LOANID,LOAN.MEMBERID,LOAN.BOOKID,MEMBER.NAME ,BOOK.BOOKNAME, LOAN.LOANDATE,LOAN.RETURNDATE,
                        LOAN.EXTENSIONAVAILABLE FROM MEMBER,BOOK,LOAN
                        WHERE LOAN.MEMBERID=MEMBER.ID AND LOAN.BOOKID=BOOK.BOOKID AND EXTENSIONAVAILABLE ='T';     
select * from loan;
delete from loan where bookid = '001';
rollback;


select MAX(LOANID) from loan;
